# Generated by Django 5.0.2 on 2024-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_number', models.CharField(max_length=3)),
                ('Student_name', models.CharField(max_length=100)),
                ('Branch_name', models.CharField(max_length=3)),
                ('Date_of_joining', models.DateTimeField()),
            ],
        ),
    ]
