# Generated by Django 5.0.2 on 2024-02-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Date_of_joining',
        ),
    ]
