# Generated by Django 5.0.2 on 2024-02-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch_name',
            field=models.CharField(max_length=4),
        ),
    ]
