# Generated by Django 5.0.2 on 2024-02-28 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date_of_joining',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 14, 18, 13, 542696)),
        ),
    ]
