# Generated by Django 5.0.2 on 2024-02-28 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date_of_joining',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 17, 37, 58, 176777)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
