# Generated by Django 5.0.2 on 2024-02-29 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date_of_joining',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 14, 32, 41, 506612)),
        ),
    ]
